### ISSUE TITLE
/settings endpoint is pinged in a endless loop

### ISSUE THREAD

**Issue by danlutz** [sw-yx/react-netlify-identity#10] opened 2019-06-09 18:06 UTC
Hi!

Your plugin is great! It worked very fine until now, but after upgrading to the latest version, I noticed in the chrome network tab that the /settings endpoint is pinged in a endless loop, which causes all components that are subscribed to the context to rerender on every ping.

Did you already notice this problem (and know an easy fix for this)?

You can see it an example on:

https://deploy-preview-5--ntrepreneur.netlify.com/

If you need any further code snippets, or have any questions, feel free to ask!

**Comment by jlengstorf** [comment] 2019-06-09 19:46
I just ran into this as well — it causes an endless render loop for components using `useIdentityContext()` as well. Repro here: https://github.com/jlengstorf/netlify-identity-loop-bug

**Comment by alexkrolick** [comment] 2019-06-09 20:11
🕵  Pretty sure the issue is that the API call to get settings always returns a new object and that causes useEffect to infinite loop:

1. https://github.com/sw-yx/react-netlify-identity/blob/2abd831b5139dacde926152839ee966db76586bc/src/index.tsx#L131-L135

2. https://github.com/netlify/gotrue-js/blob/969c2fa5a0a11c2d392b039d70d54ac482bdde31/src/index.js#L47

3. https://github.com/remerge/micro-http-client/blob/bf69f8c3dc7cea05b2ed5b74e90537ae40f7371b/src/reducers.js#L41

**Comment by sw-yx** [comment] 2019-06-10 01:50
so sorry for this bug guys, indeed i didnt notice it in my limited testing. i’ll try to fix but my confidence is a bit low since i failed to even detect this the first time.

**Comment by sw-yx** [comment] 2019-06-10 02:35
i see a little more of whats going on. this issue happens in https://react-netlify-identity.netlify.com/ but not in https://react-netlify-identity-widget.netlify.com/! i was only testing the widget, assuming that if that worked then this underlying lib worked

**Comment by sw-yx** [comment] 2019-06-10 04:02
alright i think this is fixed in `0.1.7`. please confirm?

the answer was really a two parter - a typo between `settings` and `_settings` on my end, but also i needed that memo around `useNetlifyIdentity`. https://github.com/sw-yx/react-netlify-identity/commit/e92f779c363e561f6c29b6bfdc8a9ed2e871859e#diff-38682f47b0cf12c516bc3714fc45d0fd

took a while to debug because my testing strategy sucks for this.

anyway, please update and it should work, let me know.

**Comment by sw-yx** [comment] 2019-06-10 04:12
here is [my fork of @jlengstorf's thing with the updated thing](https://github.com/sw-yx/plsdelete-netlify-identity-loop-bug) and the infinite loop is gone (jason: i had to add gatsby-ssr which you seemed to have forgotten. i guess this is the plugin we talked about! super busy this week but happy to work this up next week).

**Comment by jlengstorf** [comment] 2019-06-10 16:27
@sw-yx the fix works, but uses nested hooks, so we get warnings. I think the `useMemo` call needs to be moved inside the `useNetlifyIdentity` definition and/or it needs to use a non-hook memoization function?

**Comment by sw-yx** [comment] 2019-06-23 23:52
@jlengstorf sorry it took a while, but i've updated r-n-i to 0.1.8 and r-n-i-w to 0.1.4 (should probably sync their versions or move into monorepo...) with the useMemo moved down... hope that fixes it! it does as far as i can tell here.

**Closed by sw-yx** 2019-06-23 23:52 UTC
